[tools]
selene = { github = "Kampfkarren/selene", version = "0.20.0" }
rojo = { github = "rojo-rbx/rojo", version = "7" }
wally = { github = "UpliftGames/wally", version = "0.3.1" }
stylua = {github = "johnnymorganz/stylua", version = "0.15.2"}