name: CI Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs: 

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
  lint:
    name: Selene Lint
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Foreman
    - uses: Roblox/setup-foreman@v1
      with: 
        version: "^1.0.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Selene Lint
      run: |
        selene ./src


  # style: 
  #   name: Styling
  #   runs-on: ubuntu-latest
  #   steps:
  #    - uses: actions/checkout@v3
  #    - uses: JohnnyMorganz/stylua-action@1.0.0
  #      with:
  #       token:  ${{ secrets.GITHUB_TOKEN }}
  #       args: --check .